config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'dashboard#employee_listings'

	resources :employees do 
    collection do
      get 'download_data'
    end
  end

  get 'employees_list', to: 'dashboard#employee_listings'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
	has_attached_file :image, :styles => {:thumb => "200x250>" }
  validates_attachment_content_type :image, :content_type => /^image\/(jpg|jpeg|png)$/, :message => 'file type is not allowed (only jpg|jpeg/png images)'
	validates_uniqueness_of :email_address
	validates :phone, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def employee_listings
		if params[:advanced_search].present?
			employees = Employee.where("employee_name LIKE ?", "%#{params[:employee_name]}%")
			total_count = employees.size
		else
			employees = Employee.all
			total_count = employees.size
		end
		@total_count = total_count
		@employees = employees.paginate(:page => params[:page], :per_page => 5)
	end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
	
	def new
		@employee = Employee.new
	end

	
	def create
		@employee = Employee.new(employee_params)
		if @employee.save
		 flash[:notice] = "Employee Added Successfully!"
		 redirect_to root_path
		else
		 flash[:alert] = "Error while Adding Employee.."
		 render :new
		end
	end

	def download_data
		# byebug
    if params[:advanced_search].present?
      employees = Employee.where("employee_name LIKE ?", "%#{params[:employee_name]}%")
    else
      employees = Employee.all
    end
    # byebug
    csv_string = CSV.generate() do |csv|
      csv << ["#ID","Employee ID","Employee Name","Email Address","Phone",
              "Date of Birth","Created At","Updated At"]

      employees.each do |record|
        csv << [record.id,record.employee_id,record.employee_name,record.email_address,
                record.phone,record.date_of_birth,record.created_at,record.updated_at]
      end
    end
    send_data csv_string, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=employees-#{Date.today}.csv"
  end

	private

	
	def employee_params
		params.require(:employee).permit(:employee_id, :employee_name, :email_address, :phone, :date_of_birth, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/dashboard/employee_listings.html.erb
<br><br>
<%= form_tag '', :method => 'get', :class => 'form-inline', :autocomplete=>"off" do %>
 <%= hidden_field_tag :advanced_search, :true %>
  <div class="form-group mb-2">
    <%= text_field_tag :employee_name,params[:employee_name], class: 'form-control', placeholder: 'Employee Name',style: 'width:100%;margin-right: 16px;' %>
  </div>
  <button type="submit" class="btn btn-primary mb-2">Search</button>&nbsp;&nbsp;
  <button type="reset" class="btn btn-secondary mb-2">Reset</button>
  <div class="form-group mx-sm-3 mb-2">
  	<%= link_to '<button type="button" class="btn btn-success">Generate CSV Report</button>'.html_safe, download_data_employees_path(employee_name: "#{params[:employee_name]}",advanced_search: true),{:style=>'position: relative;left: 649px;'} %>
	</div>
<%end%>
<% if params[:advanced_search].present? %>
  <b style="color:crimson;">Search Result for Employee Name:- <%= params[:employee_name] %></b>
<%end%>
<hr>
<b>Registered Employee List</b>
<b style="float:right;">All Employees Count:- <%= @total_count %></b>
<br>
<table id="example" class="table table-striped table-bordered" style="width:100%">
  <thead>
    <tr>
    	<th></th>
      <th>Employee ID</th>
      <th>Employee Name</th>
      <th>Email Address</th>
      <th>Phone</th>
      <th>Date of Birth</th>
    </tr>
  </thead>
  <tbody>
  	<% @employees.each do |employee| %>
		  <tr>
		  	<td><%= image_tag employee.image.present? ? employee.image.url(:thumb) : "default-profile-image.png",class: 'avatar img-circle', height: '46',width:'46' %></i><br></td>
		    <td><%= employee.employee_id %></td>
        <td><%= employee.employee_name %></td>
		    <td><%= employee.email_address %></td>
		    <td><%= employee.phone %></td>
		    <td><%= employee.date_of_birth %></td>
		  </tr>
    <% end %>
  </tbody>
</table>

<div class="pull-right">
	<%= will_paginate @employees %>
</div>

<br><br>

app/views/employees/_form.html.erb
<br>
<div class="container">
    <h3 class="pseudo_border">Create New Employee</h3>
  	<hr>
  	<%= form_for @employee, :url => employees_path, method: "post", html:{class: 'form-horizontal', role: 'form', multipart: 'true'}  do |f| %>
		<div class="row">
	      
    	<div class="col-md-9">
        <%if flash[:error]%>
					<div class="error_messages alert alert-danger"><%= flash[:error] %></div>
				<% end %>
				<%if flash[:success]%>
					<div class="error_messages alert alert-success"><%= flash[:success] %></div>
				<% end %>

		    <% if @employee.errors.any? %>
		      <br>
		      <div class="error_messages alert alert-danger">
		        <ul>
		          <% for message in @employee.errors.full_messages %>
		            <li><%= message %></li>
		          <% end %>
		        </ul>
		      </div>
		    <% end %>
				<form>
			  	<div class="form-row">
				    <div class="form-group col-md-6">
			      	<label>Employee ID</label>
			      	<%= f.text_field :employee_id, {class: 'form-control'}  %>
				    </div>
				    <div class="form-group col-md-6">
			      	<label>Employee Name</label>
			      	<%= f.text_field :employee_name, {class: 'form-control'}  %>
				    </div>
					</div>
					<div class="form-row">
				    <div class="form-group col-md-6">
			      	<label>Email Address</label>
			      	<%= f.text_field :email_address, {class: 'form-control'}  %>
				    </div>

				    <div class="form-group col-md-6">
			      	<label>Phone</label>
			      	<%= f.number_field :phone, {class: 'form-control'}  %>
				    </div>
					</div>
					<div class="form-row">
				    <div class="form-group col-md-4">
			      	<label>Date of Birth</label>
			      	<%= f.date_field :date_of_birth, {class: 'form-control',max: Date.today} %>
				    </div>
				    <div class="form-group col-md-6">
			      	<label>Upload Employee Image</label><br>
			      	<%= f.file_field :image, class: 'form-control',type: :file,accept: "image/x-png,image/jpeg" %>
				    </div>
					</div>
			  
	        <div class="form-row">
				    <div class="form-group col-md-6">
				      	<input class="btn btn-primary" name="commit" type="submit" value="Save">
				      	 <input type="reset" class="btn btn-default" value="Reset">
				    </div>
					</div>
				</form>
	    </div>
		</div>
	<%end%>
</div>

<style>
	/* Chrome, Safari, Edge, Opera */
	input::-webkit-outer-spin-button,
	input::-webkit-inner-spin-button {
	  -webkit-appearance: none;
	  margin: 0;
	}

	/* Firefox */
	input[type=number] {
	  -moz-appearance: textfield;
	}
</style>

app/views/employees/new.html.erb
<%= render "employees/form" %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="/employees_list"><b>Employee Details Tracking</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
    </ul>
    <span class="navbar-text">
    	<h3><%= link_to '<button type="button" class="btn btn-outline-primary">Create Employee</button>'.html_safe, new_employee_path %></h3>
    </span>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmployeeDetailTracking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "layouts/navigation" %>

    <div class="container-fluid">
      <%= yield %>
    </div>

    <div class="footer">
      <p style="margin-top: 10px;"><h6 class="footer-content">EMPLOYEE DETAILS TRACKING - Copyright © 2020 All rights reserved</h6></p>
    </div>

  </body>
</html>